language: node_js
node_js:
- '4'
- '5'
branches:
  only:
  - master
before_script:
- export CHROME_BIN=chromium-browser
- cp protractor.conf.js.travis protractor.conf.js
- cp karma.conf.js.travis karma.conf.js
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
